python baselines.py --model_name 'resnet18'
# python baselines.py --model_name 'resnet34'
python baselines.py --model_name 'resnet50'
# python baselines.py --model_name 'resnet152'
python baselines.py --modality 'ALL' --D 36 --model_name 'resnet18'
# python baselines.py --modality 'ALL' --D 36 --model_name 'resnet34'
python baselines.py --modality 'ALL' --D 36 --model_name 'resnet50'
# python baselines.py --modality 'ALL' --D 36 --model_name 'resnet152'